# logging.yaml
version: 1
disable_existing_loggers: False
formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: DEBUG
  file:
    class: logging.handlers.RotatingFileHandler
    filename: logs/app.log
    formatter: standard
    level: INFO
    maxBytes: 10485760
    backupCount: 3
loggers:
  '':
    handlers: [console, file]
    level: DEBUG
    propagate: True
